export const mockBatches = [
  {
    id: "batch-1",
    name: "Full Stack Development - Batch A",
    description: "React, Node.js, MongoDB",
    totalTrainees: 30,
    trainer: "John Smith",
    behavioralTrainer: "Sarah Johnson",
    mentor: "Michael Brown",
    startDate: "Jan 15, 2024",
    endDate: "Apr 15, 2024",
    status: "active",
    scheduleStatus: {
      onSchedule: 18,
      behind: 8,
      advanced: 4,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 10, 2024" },
      interim: { completed: true, date: "Mar 5, 2024" },
      final: { completed: false, date: "Apr 10, 2024" },
    },
  },
  {
    id: "batch-2",
    name: "Data Science - Batch B",
    description: "Python, ML, Data Analysis",
    totalTrainees: 25,
    trainer: "Emily Davis",
    behavioralTrainer: "Robert Wilson",
    mentor: "Jessica Martinez",
    startDate: "Feb 1, 2024",
    endDate: "May 1, 2024",
    status: "graduated",
    scheduleStatus: {
      onSchedule: 25,
      behind: 0,
      advanced: 0,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 20, 2024" },
      interim: { completed: true, date: "Mar 15, 2024" },
      final: { completed: true, date: "Apr 25, 2024" },
    },
  },
  {
    id: "batch-3",
    name: "Cloud Computing - Batch C",
    description: "AWS, Azure, DevOps",
    totalTrainees: 28,
    trainer: "David Lee",
    behavioralTrainer: "Amanda White",
    mentor: "Chris Anderson",
    startDate: "Jan 20, 2024",
    endDate: "Apr 20, 2024",
    status: "active",
    scheduleStatus: {
      onSchedule: 20,
      behind: 5,
      advanced: 3,
    },
    milestones: {
      qualifier: { completed: true, date: "Feb 15, 2024" },
      interim: { completed: false, date: "Mar 20, 2024" },
      final: { completed: false, date: "Apr 15, 2024" },
    },
  },
];
